pluk:
  Image:
    Name: kuberlab/pluk
    Tag: latest
  masters: ""
  nodePort: 30803
  auth:
    enabled: false
    url: http://cloud-dealer:8082/api/v0.2/auth/whoami
    internalKey: ""
  persistence:
    fromProvider: true
    dataSize: 100Gi
    dbSize: 10Gi
    #storageClass: anything
    #storageClassDB: anything
    dbVolume:
      hostPath:
        path: /var/lib/pluk/data
    dataVolume:
      hostPath:
        path: /var/lib/pluk/data
  nodeSelector:
    enabled: false
    labels:
      pluk: pluk
  db:
    type: postgres
    # allowed:
    # type: postgres
    # type: sqlite3
    name: 'pluke'
    host: 'mlboard-postgresql'
    user: 'postgres'
    password:
      fromSecret:
        name: 'mlboard-postgresql'
        key: 'postgres-password'
      plain: ''
  envVars: []
  # - name: VAR
  #   value: val

global:
  useRBAC: true
