pluk:
  Image:
    Name: kuberlab/pluk
    Tag: latest
  masters: ""
  auth:
    enabled: false
    url: http://cloud-dealer:8082/api/v0.2/auth/whoami
    internalKey: ""
  persistence:
    fromProvider: true
    gitSize: 10Gi
    dataSize: 100Gi
    dbSize: 10Gi
    storageClass: anything
    storageClassDB: anything
    gitVolume:
      hostPath:
        path: /var/lib/pluk/git
    dataVolume:
      hostPath:
        path: /var/lib/pluk/data
  nodeSelector:
    enabled: false
    labels:
      pluk: pluk

global:
  useRBAC: true
