{{- if .Values.pluk.persistence.fromProvider -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pluk-db
spec:
  {{- if .Values.pluk.persistence.storageClass }}
  storageClassName: {{ .Values.pluk.persistence.storageClassDB | quote }}
  {{- end }}
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.pluk.persistence.dbSize }}
{{- end -}}
