apiVersion: apps/v1
kind: Deployment
metadata:
  name: pluk
  labels:
    app: kuberlab
    component: pluk
spec:
  selector:
    matchLabels:
      app: kuberlab
      component: pluk
  replicas: 1
  template:
    metadata:
      labels:
        app: kuberlab
        component: pluk
    spec:
      {{- if .Values.pluk.nodeSelector.enabled }}
      nodeSelector:
      {{- range $key, $value := .Values.pluk.nodeSelector.labels }}
        {{ $key }}: "{{ $value }}"
      {{- end }}
      {{- end }}
      containers:
        - name: pluk
          image: "{{ printf "%s:%s" .Values.pluk.Image.Name .Values.pluk.Image.Tag }}"
#          readinessProbe:
#            httpGet:
#              path: /probe
#              port: 8082
#            initialDelaySeconds: 30
#            periodSeconds: 10
#            timeoutSeconds: 3
#            successThreshold: 1
#            failureThreshold: 3
          env:
          {{- if .Values.pluk.auth.enabled }}
          - name: AUTH_VALIDATION
            value: "{{ .Values.pluk.auth.url }}"
          {{- end }}
          {{- if .Values.pluk.masters }}
          - name: MASTERS
            value: "{{ .Values.pluk.masters }}"
          {{- end }}
          - name: DEBUG
            value: "false"
          - name: DATA_DIR
            value: "/data"
          {{- if .Values.pluk.auth.internalKey }}
          - name: INTERNAL_KEY
            valueFrom:
              secretKeyRef:
                name: pluk-key
                key: internalKey
          {{- end }}
          - name: DB_TYPE
            value: {{ .Values.pluk.db.type }}
          - name: DB_NAME
            value: {{ .Values.pluk.db.name }}
          - name: DB_HOST
            value: {{ .Values.pluk.db.host }}
          - name: DB_USER
            value: {{ .Values.pluk.db.user }}
          {{- if or .Values.pluk.db.password.plain (and .Values.pluk.db.password.fromSecret.name .Values.pluk.db.password.fromSecret.key)}}
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
              {{- if and .Values.pluk.db.password.fromSecret.name .Values.pluk.db.password.fromSecret.key }}
                name: {{ .Values.pluk.db.password.fromSecret.name }}
                key: {{ .Values.pluk.db.password.fromSecret.key }}
              {{- else }}
                {{- if .Values.pluk.db.password.plain }}
                name: pluk-key
                key: postgres-password
                {{- end }}
              {{- end }}
          {{- end }}
          {{- range .Values.pluk.envVars }}
          - name: {{ .name }}
            value: '{{ .value }}'
          {{- end }}
          ports:
          - containerPort: 8082
            name: api
          - containerPort: 8085
            name: grpc
          volumeMounts:
          - name: data
            mountPath: /data
          - name: db
            mountPath: /pluk
      volumes:
      - name: data
        {{- if .Values.pluk.persistence.fromProvider }}
        persistentVolumeClaim:
          claimName: pluk-data
        {{- else }}
{{ toYaml .Values.pluk.persistence.dataVolume | indent 8 }}
        {{- end }}
      - name: db
        {{- if .Values.pluk.persistence.fromProvider }}
        persistentVolumeClaim:
          claimName: pluk-db
        {{- else }}
{{ toYaml .Values.pluk.persistence.dbVolume | indent 8 }}
        {{- end }}
