apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuberlab
    component: pluk
  name: pluk
spec:
  ports:
  - name: http
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: kuberlab
    component: pluk
