{{- if or .Values.pluk.auth.internalKey .Values.pluk.db.password.plain }}
apiVersion: v1
data:
  internalKey: {{ .Values.pluk.auth.internalKey | b64enc | quote }}
  {{- if .Values.pluk.db.password.plain }}
  postgres-password: {{ .Values.pluk.db.password.plain | b64enc | quote }}
  {{- end }}
kind: Secret
metadata:
  name: pluk-key
type: Opaque
{{- end }}
