apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuberlab
    component: pluk
  name: pluk
spec:
  type: NodePort
  ports:
  - name: http
    port: 8082
    protocol: TCP
    targetPort: 8082
    nodePort: {{ .Values.pluk.nodePort }}
  - name: grpc
    port: 8085
    protocol: TCP
    targetPort: 8085
    nodePort: 30805
  selector:
    app: kuberlab
    component: pluk
